[global]
error_log = syslog
syslog.ident = php-fpm

[www]
listen = 127.0.0.1:9000
pm = static
pm.max_children = 5
clear_env = no

php_admin_value[memory_limit] = 512M
php_admin_value[post_max_size] = 128M
php_admin_value[upload_max_filesize] = 128M
php_admin_value[opcache.enable] = 1
php_admin_value[opcache.jit] = tracing
php_admin_value[opcache.jit_buffer_size] = 64M

php_admin_flag[display_errors] = off
php_admin_flag[log_errors] = on
php_admin_value[variables_order] = "EGPCS"
